---
- name: Set read permission on logdir
  file:
    path: "{{nginx_logdir}}"
    state: directory
    owner: "{{nginx_user}}"
    group: "{{nginx_group}}"
    mode: 0755

- name: Allow Nginx to listen on tcp port
  seport:
    ports: "{{nginx_extra_server.port}}"
    proto: tcp
    setype: http_port_t
    state: present

- name: Allow Nginx to access the content tree
  sefcontext:
    target: "{{nginx_extra_server.docroot}}(/.*?)"
    setype: httpd_sys_content_t
    state: present

- name: Template of server.conf
  template:
    src: server.conf.j2
    dest: "{{nginx_dir}}/conf.d/server.conf"
    mode: 0644
  vars:
    port: "{{nginx_extra_server.port}}"
    server_name: "{{nginx_extra_server.server_name}}"
    docroot: "{{nginx_extra_server.docroot}}"
    logdir: "{{nginx_logdir}}"
    log_locations: "{{nginx_log_locations}}"
  notify: Restart_nginx.service
