---
- name: Install Nginx package
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Template of nginx.conf
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: 0644
  vars:
    nginx_user: www-data
  notify: Restart_nginx

- name: Get stats of monitrc
  stat: 
    path: /etc/monit/monitrc
    get_md5: no
    get_checksum: no
  register: st_monitrc

- name: Template of nginx.monit
  template:
    src: nginx.monit.j2
    dest: /etc/monit/conf.d/nginx.monit
    mode: 0644
  vars:
    start_program: '/usr/sbin/service nginx start'
    stop_program: '/usr/sbin/service nginx stop'
  when: st_monitrc.stat.exists
  notify: Restart_monit
