---
# Provision an EC2 instance and configure the given role with Apache2 as the web frontend
## Create EC2 instances
- hosts: localhost
  connection: local
  gather_facts: false

  roles:
    - ec2_launcher

## Config EC2 instances
- hosts: ec2hosts
  gather_facts: true
  become: true
  vars:
    ansible_ssh_private_key_file: "{{pem_file}}"
    wrapper_role: idservice

  roles:
    - common
    - { role: "{{wrapper_role}}", web_frontend: apache }
