---
# Query EC2 instances
- hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - include_vars: roles/ec2_launcher/defaults/main.yml
    - include: roles/ec2_launcher/tasks/query.yml
