---
## Create EC2 instances
- hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - ec2_launcher

## Config EC2 instances
- hosts: ec2hosts
  gather_facts: false
  remote_user: ubuntu
  become: true
  vars:
    ansible_ssh_private_key_file: /Users/ylu31/.ssh/ylu.pem

  roles:
    - common
