---
# Provision an EC2 instance and configure the role of rotation with Apache2 as the web frontend
## Create EC2 instances
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    aws_region: us-east-1
    image_id: ami-ae7bfdb8
    vpc_id: vpc-745a650c
    subnet_id: subnet-47eb1e48
    iam_role:
    pause_for_up: 30
    extra_sg_rules:
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0

  roles:
    - ec2_launcher

## Config EC2 instances
- hosts: ec2hosts
  gather_facts: true
  become: true
  vars:
    ansible_ssh_private_key_file: "{{pem_file}}"

  roles:
    - common
    - rotation
