---
# Terminate EC2 instances
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    region: us-east-2

  vars_files:
    - "group_vars/{{region}}.yml"
    - group_vars/extra_sg_rules.yml
    - "group_vars/service/{{wrapper_service}}.yml"

  roles:
    - ec2_destroyer
