---
- name: Install Apache package
  package:
    name: "{{apache2_pkg_name}}"
    state: present
    update_cache: yes

- name: Install mod_ssl
  yum:
    name: mod_ssl
    state: present
    update_cache: yes
  when: ansible_distribution in ['RedHat', 'CentOS']

- name: Copy server.crt and server.key
  copy:
    src: "{{item}}"
    dest: "{{apache2_dir}}/"
    mode: 0600
  with_items:
    - server.crt
    - server.key
  notify: Restart_apache.service

- name: Copy httpd.conf
  copy:
    src: "{{apache2_pkg_name}}.conf"
    dest: "{{apache2_conf_dir}}/"
    mode: 0644
  notify: Restart_apache.service

- name: Template of default.conf.j2
  template:
    src: default.conf.j2
    dest: "{{apache2_dir}}/{{apache2_default_conf}}"
    mode: 0644
  vars:
    locations: "{{apache2_locations}}"
    conf_dir: "{{apache2_dir}}"
    mods_dir: "{{apache2_modsdir}}"
  notify: Restart_apache.service

- name: Get stats of monitrc
  stat:
    path: "{{monit_dir}}/monitrc"
    get_md5: no
    get_checksum: no
  register: st_monitrc

- name: Template of apache2.monit
  template:
    src: apache2.monit.j2
    dest: "{{monit_includedir}}/apache2.monit"
    mode: 0644
  vars:
    pidfile: "{{apache2_pidfile}}"
    start_program: '/usr/bin/systemctl start {{apache2_pkg_name}}'
    stop_program: '/usr/bin/systemctl stop {{apache2_pkg_name}}'
  when: st_monitrc.stat.exists
  notify: Restart_monit.service
