---
- name: Install Apache2 package
  apt:
    name: "{{apache2_pkg_name}}"
    state: present
    update_cache: yes

- name: Copy server.crt and server.key
  copy:
    src: "{{item}}"
    dest: "{{apache2_dir}}/"
    mode: 0600
  with_items:
    - server.crt
    - server.key
  notify: Restart_apache

- name: Copy apache2.conf
  copy:
    src: apache2.conf
    dest: "{{apache2_dir}}/"
    mode: 0644
  notify: Restart_apache

- name: Template of default.conf.j2
  template:
    src: default.conf.j2
    dest: "{{apache2_dir}}/sites-available/000-default.conf"
    mode: 0644
  vars:
    locations: "{{apache2_locations}}"
    conf_dir: "{{apache2_dir}}"
    mods_dir: "{{apache2_modsdir}}"
  notify: Restart_apache

- name: Get stats of monitrc
  stat: 
    path: "{{monit_dir}}/monitrc"
    get_md5: no
    get_checksum: no
  register: st_monitrc

- name: Template of apache2.monit
  template:
    src: apache2.monit.j2
    dest: "{{monit_includedir}}/apache2.monit"
    mode: 0644
  vars:
    pidfile: "{{apache2_pidfile}}"
    start_program: '/usr/sbin/service {{apache2_pkg_name}} start'
    stop_program: '/usr/sbin/service {{apache2_pkg_name}} stop'
  when: st_monitrc.stat.exists
  notify: Restart_monit
