---
- name: Create group account for qb
  group:
    name: "{{qbroker_group}}"
    state: present

- name: Create user account for qbadm
  user:
    name: "{{qbroker_user}}"
    comment: QBroker
    group: "{{qbroker_group}}"
    state: present
    shell: /bin/bash
    home: "{{qbroker_dir}}"
    createhome: no

- name: Create dir of /var/cache/ansible
  file:
    path: /var/cache/ansible
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Get stats of qbroker.tgz
  stat:
    path: "/var/cache/ansible/{{qbroker_tarball}}"
    get_md5: no
    get_checksum: no
  register: st_qb_tarball

- name: Get the tarball
  get_url:
    url: "{{qbroker_repo_url}}/{{qbroker_tarball}}"
    dest: /var/cache/ansible/
    validate_certs: "{{qbroker_validate_certs}}"
  when: not st_qb_tarball.stat.exists
  register: new_archive_qb

- name: Get stats of /opt/qbroker
  stat:
    path: "{{qbroker_dir}}"
    get_md5: no
    get_checksum: no
  register: st_qbroker

- name: Unarchive source
  unarchive:
    src: "/var/cache/ansible/{{qbroker_tarball}}"
    dest: /opt
    remote_src: yes
    owner: "{{qbroker_user}}"
    group: "{{qbroker_group}}"
  when: new_archive_qb|changed or not st_qbroker.stat.exists
