---
- name: Create dir for the web service
  file:
    path: "{{qbroker_dir}}/flow/{{qbroker_service_id}}"
    state: directory
    owner: "{{tomcat_user}}"
    group: "{{tomcat_group}}"
    mode: 0755

- name: Template of context.xml
  template:
    src: context.xml.j2
    dest: "{{tomcat_dir}}/Catalina/localhost/{{qbroker_webapp_context}}.xml"
    owner: root
    group: "{{tomcat_group}}"
    mode: 0644
  vars:
    path: "{{qbroker_webapp_context}}"
    context: "{{qbroker_webapp_context}}"
    qb_dir: "{{qbroker_dir}}"
  notify: Restart_tomcat

- name: Create dir of webservice/WEB-INF/lib
  file:
    path: "{{qbroker_dir}}/{{item}}"
    state: directory
    owner: "{{tomcat_user}}"
    group: "{{tomcat_group}}"
    mode: 0755
  with_items:
    - "{{qbroker_webapp_context}}"
    - "{{qbroker_webapp_context}}/WEB-INF"
    - "{{qbroker_webapp_context}}/WEB-INF/lib"

- name: Copy web.xml
  copy:
    src: "../../{{qbroker_webapp_context}}/files/web.xml"
    dest: "{{qbroker_dir}}/{{qbroker_webapp_context}}/WEB-INF/"
    owner: "{{tomcat_user}}"
    group: "{{tomcat_group}}"
    mode: 0644
  notify: Restart_tomcat

- name: Copy jsp files
  copy:
    src: "../../{{qbroker_webapp_context}}/files/jsp/{{item}}"
    dest: "{{qbroker_dir}}/{{qbroker_webapp_context}}/"
    owner: "{{tomcat_user}}"
    group: "{{tomcat_group}}"
    mode: 0644
  with_items: "{{qbroker_jsp_files}}"

- name: Copy json files
  copy:
    src: "../../{{qbroker_webapp_context}}/files/flow/{{item}}"
    dest: "{{qbroker_dir}}/flow/{{qbroker_service_id}}/"
    owner: "{{tomcat_user}}"
    group: "{{tomcat_group}}"
    mode: 0644
  with_items: "{{qbroker_json_files}}"
  notify: Restart_tomcat

- name: Copy jar files
  copy:
    src: "{{qbroker_dir}}/lib/{{item}}"
    dest: "{{qbroker_dir}}/{{qbroker_webapp_context}}/WEB-INF/lib/"
    remote_src: yes
    force: no
    owner: "{{tomcat_user}}"
    group: "{{tomcat_group}}"
    mode: 0644
  with_items: "{{qbroker_jar_files}}"
  notify: Restart_tomcat
