---
dependencies:
  - role: monit
  - role: java
  - { role: sonicmq, when: mbservice_mq == 'sonicmq' }
  - { role: activemq, when: mbservice_mq != 'sonicmq' }
  - role: tomcat
  - role: qbroker
  - { role: nginx, when: web_frontend == 'nginx' }
  - { role: apache2, when: web_frontend == 'apache' }
