---
- name: Copy server.crt and server.key
  copy:
    src: "{{item}}"
    dest: "{{apache2_dir}}/"
    mode: 0600
  with_items:
    - server.crt
    - server.key
  notify: Restart_apache

- name: Copy apache2.conf
  copy:
    src: apache2.conf
    dest: "{{apache2_dir}}/"
    mode: 0644
  notify: Restart_apache

- name: Template of default.conf.j2
  template:
    src: default.conf.j2
    dest: "{{apache2_dir}}/sites-available/000-default.conf"
    mode: 0644
  vars:
    conf_dir: "{{apache2_dir}}"
    mods_dir: "{{apache2_modsdir}}"
  notify: Restart_apache

- name: Template of index.html.j2
  template:
    src: index.html.j2
    dest: "/var/www/html/index.html"
    mode: 0644
  vars:
    hostname: "{{ansible_hostname}}"
