---
- name: Create group account for activemq
  group:
    name: "{{activemq_group}}"
    state: present

- name: Create user account for activemq
  user:
    name: "{{activemq_user}}"
    comment: ActiveMQ
    group: "{{activemq_group}}"
    state: present
    shell: /sbin/nologin
    createhome: no

- name: Create dir of /var/cache/ansible
  file:
    path: /var/cache/ansible
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Gets the tarball
  get_url:
    url: "{{activemq_repo_url}}/{{activemq_version}}/{{activemq_pkg_name}}-{{activemq_version}}-bin.tar.gz"
    dest: /var/cache/ansible/
  register: new_archive

- name: Get stats of /opt/activemq
  stat:
    path: "/opt/{{activemq_pkg_name}}-{{activemq_version}}"
    get_md5: no
    get_checksum: no
  register: st_activemq

- name: Unarchive source
  unarchive:
    src: "/var/cache/ansible/{{activemq_pkg_name}}-{{activemq_version}}-bin.tar.gz"
    dest: /opt
    remote_src: yes
    owner: "{{activemq_user}}"
    group: "{{activemq_group}}"
  when: new_archive|changed or not st_activemq.stat.exists

- name: Create symlink of /opt/activemq
  file:
    src: "/opt/{{activemq_pkg_name}}-{{activemq_version}}"
    dest: /opt/activemq
    state: link

- name: Template of configs
  template:
    src: "{{item}}.j2"
    dest: "/opt/activemq/conf/{{item}}"
    owner: "{{activemq_user}}"
    group: "{{activemq_group}}"
    mode: 0644
  with_items:
    - activemq.xml
    - jetty.xml
    - users.properties
    - groups.properties
    - credentials.properties
  notify: Restart_activemq.service

- name: Copy activemq.service
  copy:
    src: activemq.service
    dest: /usr/lib/systemd/system/
    mode: 0644
  notify: Restart_activemq.service

- name: Get stats of monitrc
  stat:
    path: /etc/monitrc
    get_md5: no
    get_checksum: no
  register: st_monitrc

- name: Template of activemq.monit
  template:
    src: activemq.monit.j2
    dest: /etc/monit.d/activemq.monit
    mode: 0644
  vars:
    pidfile: /opt/activemq/data/activemq.pid
    start_program: '/usr/bin/systemctl start activemq'
    stop_program: '/usr/bin/systemctl stop activemq'
  when: st_monitrc.stat.exists
  notify: Restart_monit.service
