---
- name: Create group account for activemq
  group:
    name: "{{amq_group}}"
    state: present

- name: Create user account for activemq
  user:
    name: "{{amq_user}}"
    comment: ActiveMQ
    group: "{{amq_group}}"
    state: present
    shell: /sbin/nologin
    createhome: no

- name: Create dir of /opt
  file:
    path: /opt
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Create dir of /var/cache/ansible
  file:
    path: /var/cache/ansible
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Gets the tarball
  get_url:
    url: "{{amq_repo_url}}/{{amq_version}}/{{amq_pkg_name}}-{{amq_version}}-bin.tar.gz"
    dest: /var/cache/ansible/
  register: new_archive

- name: Get stats of /opt/activemq
  stat:
    path: "/opt/{{amq_pkg_name}}-{{amq_version}}"
    get_md5: no
    get_checksum: no
  register: st_activemq

- name: Unarchive source
  unarchive:
    src: "/var/cache/ansible/{{amq_pkg_name}}-{{amq_version}}-bin.tar.gz"
    dest: /opt
    remote_src: yes
    owner: "{{amq_user}}"
    group: "{{amq_group}}"
  when: new_archive|changed or not st_activemq.stat.exists

- name: Create symlink of /opt/activemq
  file:
    src: "/opt/{{amq_pkg_name}}-{{amq_version}}"
    dest: /opt/activemq
    state: link

- name: Template of configs 
  template:
    src: "{{item}}.j2"
    dest: "/opt/activemq/conf/{{item}}"
    owner: "{{amq_user}}"
    group: "{{amq_group}}"
    mode: 0644
  with_items:
    - activemq.xml
    - jetty.xml
    - users.properties
    - groups.properties
    - credentials.properties
  notify: Restart_activemq

- name: Copy activemq.service
  copy:
    src: activemq.service
    dest: /lib/systemd/system/
    mode: 0644
  notify: Restart_activemq

- name: Get stats of monitrc
  stat: 
    path: /etc/monit/monitrc
    get_md5: no
    get_checksum: no
  register: st_monitrc

- name: Template of activemq.monit
  template:
    src: activemq.monit.j2
    dest: /etc/monit/conf.d/activemq.monit
    mode: 0644
  vars:
    pidfile: /var/run/activemq/main.pid
    start_program: '/usr/sbin/service activemq start'
    stop_program: '/usr/sbin/service activemq stop'
  when: st_monitrc.stat.exists
  notify: Restart_monit
