---
- name: Include vars of ec2_launcher
  include_vars:
    file: ../../ec2_launcher/vars/main.yml
    name: ec2

- name: Query sg info
  local_action:
    module: ec2_group_facts
    region: "{{ec2.aws_region}}"
    filters:
      vpc_id: "{{ec2.vpc_id}}"
      group_name: "{{ec2.sg_name}}"
  become: no
  register: ec2_sg_info

- name: Initialize an empty list
  set_fact:
    sg_rules: []

- name: Merge extra_sg_rules to sg_rules
  set_fact:
    sg_rules: "{{ec2.sg_rules}} + {{extra_sg_rules}}"
  when: extra_sg_rules|length > 0

- name: Update security group
  local_action:
    module: ec2_group
    name: "{{ec2.sg_name}}"
    description: "{{ec2_sg_info.security_groups[0].description}}"
    region: "{{ec2.aws_region}}"
    vpc_id: "{{ec2.vpc_id}}"
    rules: "{{sg_rules}}"
    rules_egress:
      - proto: all
        cidr_ip: 0.0.0.0/0
  become: no
  when: sg_rules|length > 0 and ec2_sg_info.security_groups|length > 0
