---
- name: Install mysql-server package
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
  with_items:
    - "{{mysql_pkg_name}}"
    - python-mysqldb

- name: Make sure mysqld is up
  service:
    name: mysql
    state: started
    enabled: yes

- name: Get stats of .my.cnf
  stat: 
    path: ~/.my.cnf
    get_md5: no
    get_checksum: no
  register: st_mycnf

- name: Update MySQL root password
  mysql_user:
    name: root
    host: "{{item}}"
    password: "{{mysql_root_passwd}}"
    state: present
  with_items:
    - "{{ansible_hostname}}"
    - 127.0.0.1
    - ::1
    - localhost
  when: not st_mycnf.stat.exists

- name: Template for .my.cnf
  template:
    src: root.cnf.j2
    dest: ~/.my.cnf
    mode: 0600

- name: Ensure Anonymous users are not in the database
  mysql_user:
    name: ''
    host: "{{item}}"
    state: absent
  with_items:
    - "{{ansible_hostname}}"
    - localhost

- name: Remove the test database
  mysql_db:
    name: test 
    state: absent

- name: Create user for the db
  mysql_user:
    name: "{{mysql_db_user}}"
    password: "{{mysql_db_passwd}}"
    priv: '*.*:ALL'
    state: present

- name: Create database
  mysql_db:
    name: "{{mysql_db_name}}"
    encoding: utf8
    state: present

- name: Check table of services
  command: /usr/bin/mysql "{{mysql_db_name}}" -e 'show columns from services'
  register: table_check
  failed_when: False
  changed_when: False

- name: Copy eventid.sql
  copy:
    src: eventid.sql
    dest: /tmp/
    mode: 0644
  when: "'service_id' not in table_check.stdout"

- name: Load schema of eventid.sql
  mysql_db:
    name: "{{mysql_db_name}}"
    state: import
    target: /tmp/eventid.sql
  when: "'service_id' not in table_check.stdout"

- name: Cleanup eventid.sql
  file:
    path: /tmp/eventid.sql
    state: absent

- name: Get stats of monitrc
  stat: 
    path: /etc/monit/monitrc
    get_md5: no
    get_checksum: no
  register: st_monitrc

- name: Copy mysqld.monit
  copy:
    src: mysqld.monit
    dest: /etc/monit/conf.d/
    mode: 0644
  when: st_monitrc.stat.exists
  notify: Restart_monit
