---
- name: Template of Flow.json
  template:
    src: Flow.json.j2
    dest: "{{qbroker_dir}}/flow/{{qbroker_service_id}}/Flow.json"
    owner: "{{tomcat_user}}"
    group: "{{tomcat_group}}"
    mode: 0644
  vars:
    id: "{{qbroker_service_id}}"
    qb_dir: "{{qbroker_dir}}"
    log_dir: "{{tomcat_logdir}}"
  notify: Restart_tomcat.service

- name: Template of pstr_msg.json
  template:
    src: pstr_msg.json.j2
    dest: "{{qbroker_dir}}/flow/{{qbroker_service_id}}/pstr_msg.json"
    owner: "{{tomcat_user}}"
    group: "{{tomcat_group}}"
    mode: 0644
  vars:
    url: "{{mbservice_mq_url}}"
    context_factory: "{{mbservice_context_factory}}"
    qcf: "{{mbservice_qcf}}"
    queue: "{{mbservice_queue}}"
    user: "{{mbservice_mq_user}}"
    passwd: "{{mbservice_mq_passwd}}"
  notify: Restart_tomcat.service
