---
- name: Template of Flow.json
  template:
    src: Flow.json.j2
    dest: "{{qbroker_dir}}/flow/{{qbroker_service_id}}/Flow.json"
    owner: "{{tomcat_user}}"
    group: "{{tomcat_group}}"
    mode: 0644
  vars:
    id: "{{qbroker_service_id}}"
    qb_dir: "{{qbroker_dir}}"
    log_dir: "{{tomcat_logdir}}"
  notify: Restart_tomcat

- name: Template of pstr_msg.json
  template:
    src: pstr_msg.json.j2
    dest: "{{qbroker_dir}}/flow/{{qbroker_service_id}}/pstr_msg.json"
    owner: "{{tomcat_user}}"
    group: "{{tomcat_group}}"
    mode: 0644
  notify: Restart_tomcat
