---
- name: Copy tomcat_web.xml to enable PUT
  copy:
    src: tomcat_web.xml
    dest: /etc/tomcat7/web.xml
    owner: root
    group: tomcat7
    mode: 0644
  notify: Restart_tomcat

- name: Copy mbservice.xml
  copy:
    src: mbservice.xml
    dest: /etc/tomcat7/Catalina/localhost/
    owner: root
    group: tomcat7
    mode: 0644
  notify: Restart_tomcat

- name: Create dir of mbservice/WEB-INF/lib
  file:
    path: "/opt/qbroker/{{item}}"
    state: directory
    owner: tomcat7
    group: tomcat7
    mode: 0755
  with_items:
    - mbservice
    - mbservice/WEB-INF
    - mbservice/WEB-INF/lib

- name: Copy web.xml
  copy:
    src: web.xml
    dest: /opt/qbroker/mbservice/WEB-INF/
    owner: tomcat7
    group: tomcat7
    mode: 0644
  notify: Restart_tomcat

- name: Copy jsp files
  copy:
    src: "jsp/{{item}}"
    dest: /opt/qbroker/mbservice/
    owner: tomcat7
    group: tomcat7
    mode: 0644
  with_items: "{{flow_jsp_files}}"

- name: Create dir of MB
  file:
    path: /opt/qbroker/flow/MB
    state: directory
    owner: tomcat7
    group: tomcat7
    mode: 0755

- name: Copy json files
  copy:
    src: "flow/{{item}}"
    dest: /opt/qbroker/flow/MB/
    owner: tomcat7
    group: tomcat7
    mode: 0644
  with_items: "{{flow_json_files}}"
  notify: Restart_tomcat

- name: Template of Flow.json
  template:
    src: Flow.json.j2
    dest: /opt/qbroker/flow/MB/Flow.json
    owner: tomcat7
    group: tomcat7
    mode: 0644
  vars:
    log_dir: /var/log/tomcat7
  notify: Restart_tomcat

- name: Template of pstr_msg.json
  template:
    src: pstr_msg.json.j2
    dest: /opt/qbroker/flow/MB/pstr_msg.json
    owner: tomcat7
    group: tomcat7
    mode: 0644
  notify: Restart_tomcat

- name: Copy jar files
  copy:
    src: "/opt/qbroker/lib/{{item}}"
    dest: /opt/qbroker/mbservice/WEB-INF/lib/
    remote_src: yes
    force: no
    owner: tomcat7
    group: tomcat7
    mode: 0644
  with_items: "{{flow_jar_files}}"
  notify: Restart_tomcat
