---
- name: Install Tomcat package
  yum:
    name: "{{tomcat_pkg_name}}"
    state: present
    update_cache: yes

- name: Get stats of monitrc
  stat:
    path: "{{monit_dir}}/monitrc"
    get_md5: no
    get_checksum: no
  register: st_monitrc

- name: Template of tomcat.monit
  template:
    src: tomcat.monit.j2
    dest: "{{monit_includedir}}/tomcat.monit"
    mode: 0644
  vars:
    pattern: '.base={{tomcat_basedir}} '
    start_program: '/usr/bin/systemctl start {{tomcat_pkg_name}}'
    stop_program: '/usr/bin/systemctl stop {{tomcat_pkg_name}}'
  when: st_monitrc.stat.exists
  notify: Restart_monit.service

- name: Set seboolean
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes
