---
- name: Install Tomcat package
  apt:
    name: "{{tomcat_pkg_name}}"
    state: present
    update_cache: yes

- name: Template of web.xml
  template:
    src: web.xml.j2
    dest: "{{tomcat_dir}}/web.xml"
    owner: root
    group: "{{tomcat_group}}"
    mode: 0644
  vars:
    is_readonly: "{{tomcat_is_readonly}}"
  notify: Restart_tomcat

- name: Get stats of monitrc
  stat:
    path: "{{monit_dir}}/monitrc"
    get_md5: no
    get_checksum: no
  register: st_monitrc

- name: Template of tomcat.monit
  template:
    src: tomcat.monit.j2
    dest: "{{monit_includedir}}/tomcat.monit"
    mode: 0644
  vars:
    pattern: '.base={{tomcat_basedir}} '
    port: "{{tomcat_port}}"
    start_program: '/usr/sbin/service {{tomcat_pkg_name}} start'
    stop_program: '/usr/sbin/service {{tomcat_pkg_name}} stop'
  when: st_monitrc.stat.exists
  notify: Restart_monit
