---
- name: Copy server.crt and server.key
  copy:
    src: "{{item}}"
    dest: /etc/httpd/
    mode: 0600
  with_items:
    - server.crt
    - server.key
  notify: Restart_apache.service

- name: Copy httpd.conf
  copy:
    src: httpd.conf
    dest: /etc/httpd/conf/
    mode: 0644
  notify: Restart_apache.service

- name: Template of default.conf.j2
  template:
    src: default.conf.j2
    dest: /etc/httpd/conf.d/ssl.conf
    mode: 0644
  vars:
    conf_dir: /etc/httpd
    mods_dir: /etc/httpd/modules
  notify: Restart_apache.service
