---
- name: Copy idservice.xml
  copy:
    src: idservice.xml
    dest: /etc/tomcat/Catalina/localhost/
    owner: root
    group: tomcat
    mode: 0644
  notify: Restart_tomcat.service

- name: Create dir of idservice/WEB-INF/lib
  file:
    path: "/opt/qbroker/{{item}}"
    state: directory
    owner: tomcat
    group: tomcat
    mode: 0755
  with_items:
    - idservice
    - idservice/WEB-INF
    - idservice/WEB-INF/lib

- name: Copy web.xml
  copy:
    src: web.xml
    dest: /opt/qbroker/idservice/WEB-INF/
    owner: tomcat
    group: tomcat 
    mode: 0644
  notify: Restart_tomcat.service

- name: Copy jsp files
  copy:
    src: "jsp/{{item}}"
    dest: /opt/qbroker/idservice/
    owner: tomcat
    group: tomcat
    mode: 0644
  with_items: "{{idservice_jsp_files}}"

- name: Create dir of ID
  file:
    path: /opt/qbroker/flow/ID
    state: directory
    owner: tomcat
    group: tomcat
    mode: 0755

- name: Copy json files
  copy:
    src: "flow/{{item}}"
    dest: /opt/qbroker/flow/ID/
    owner: tomcat
    group: tomcat
    mode: 0644
  with_items: "{{idservice_json_files}}"
  notify: Restart_tomcat.service

- name: Template of Flow.json
  template:
    src: Flow.json.j2
    dest: /opt/qbroker/flow/ID/Flow.json
    owner: tomcat
    group: tomcat
    mode: 0644
  vars:
    log_dir: /var/log/tomcat
  notify: Restart_tomcat.service

- name: Template of pstr_db_query.json
  template:
    src: pstr_db_query.json.j2
    dest: /opt/qbroker/flow/ID/pstr_db_query.json
    owner: tomcat
    group: tomcat
    mode: 0644
  vars:
    db_name: eventdb
    db_port: 5432
    db_user: eventdba
    db_passwd: secret
  notify: Restart_tomcat.service

- name: Copy jar files
  copy:
    src: "/opt/qbroker/lib/{{item}}"
    dest: /opt/qbroker/idservice/WEB-INF/lib/
    remote_src: yes
    force: no
    owner: tomcat
    group: tomcat
    mode: 0644
  with_items: "{{idservice_jar_files}}"
  notify: Restart_tomcat.service
