---
- name: Copy server.crt and server.key
  copy:
    src: "{{item}}"
    dest: /etc/nginx/
    mode: 0600
  with_items:
    - server.crt
    - server.key
  notify: Restart_nginx.service

- name: Copy default.conf with proxy_pass
  copy:
    src: default.conf
    dest: /etc/nginx/conf.d/
    mode: 0644
  notify: Restart_nginx.service
