---
- name: Terminate queried instances in {{aws_region}}
  ec2:
    state: 'absent'
    region: "{{aws_region}}"
    instance_ids: "{{item.id}}"
  with_items: "{{ec2_info.instances}}"
  when: ec2_info.instances|length > 0

- name: Pause for a minute
  pause:
    seconds: 60
  when: ec2_info.instances|length > 0

- name: Take security group of {{sg_name}} down
  ec2_group:
    name: "{{sg_name}}"
    region: "{{aws_region}}"
    state: 'absent'
  when: ec2_info.instances|length > 0
